# Generated by Django 6.0 on 2025-12-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('IG', 'Instagram'), ('LI', 'LinkedIn'), ('TW', 'Twitter')], max_length=2)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('logged_in', models.BooleanField(default=False, help_text='Current login status')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last successful login time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
