# Generated by Django 6.0 on 2025-12-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='cookies',
            field=models.JSONField(blank=True, default=dict, help_text='Browser cookies for maintaining session', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='cookies_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time cookies were updated', null=True),
        ),
    ]
