# Generated by Django 6.0 on 2025-12-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_socialaccount_cookies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='in_use',
            field=models.BooleanField(default=False, help_text='Whether this cookie is currently being used'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='Last time this cookie was provided/used', null=True),
        ),
    ]
