# Generated by Django 6.0 on 2025-12-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_socialaccount_in_use_socialaccount_last_used_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('username', 'platform')},
        ),
    ]
