# Generated by Django 6.0 on 2025-12-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_socialaccount_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='consecutive_failures',
            field=models.IntegerField(default=0, help_text='Number of consecutive failures for this cookie'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='failure_reason',
            field=models.CharField(blank=True, help_text='Reason for last cookie failure', max_length=255, null=True),
        ),
    ]
