# Generated by GitHub Copilot on 2026-02-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_socialaccount_consecutive_failures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='last_validated_at',
            field=models.DateTimeField(blank=True, help_text='Last time this cookie was validated before allocation', null=True),
        ),
    ]
